---
# handlers file for immotep
- name: Restart immotep
  ansible.builtin.systemd:
    name: immotep
    state: restarted
    enabled: true
  when: "'immotep.service' in ansible_facts.services"

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true

- name: Reload immotep
  ansible.builtin.systemd:
    name: immotep
    daemon_reload: true
    state: reloaded
    enabled: true
  when: "'immotep.service' in ansible_facts.services"
