---
# vars file for immotep
gcp_cred_kind: serviceaccount
gcp_svc_file: ~/.gcp_svc_tutogc.json
gcp_project: tutogc
gcp_region: europe-west4
gcp_zone: europe-west4-c

pgdb_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33396133666330333937613836326637343566363766663931353664666438393064336437356166
          6338393436663561653839633533356364613131656564300a353861353633313566313266616662
          61373033383262366139653132623138646336393864383637363464376534643939633764313839
          3332306333646130330a396161393630636534386665313363313834323139613561386139346138
          3636